# fly.toml app configuration file generated for arcana-vault-api-2026 on 2026-02-21T15:42:54+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "arcana-vault-api-2026"
primary_region = "sin"

[env]
APP_PORT = "8000"
ENVIRONMENT = "production"

[http_service]
auto_start_machines = false
auto_stop_machines = false
force_https = true
internal_port = 8_000
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpus = 1
memory = "512mb"
memory_mb = 512
size = "shared-cpu-1x"
